### ISSUE TITLE
Coverage badge shows "coverage unknown"

### ISSUE THREAD

**Issue by delgrecoj** [Accelegator/accelegator#105]
![2017-11-14-134026_1920x1080_scrot](https://user-images.githubusercontent.com/21695244/32797965-691ebc72-c941-11e7-8329-2e93a3dbec24.png)

**Comment by delgrecoj** [comment]
Screenshot above is the page that clicking on the badge at the bottom of the README file brought me to.  It seems to suggest that coveralls is perhaps not configured correctly just yet.

**Comment by sutterj** [comment]
Travis says that the command coveralls is not found.  That message that you screenshotted goes away for me after I hit refresh.  Then it says that there are no jobs for this repo.

**Comment by sutterj** [comment]
It is missing the pip3 install coveralls in the travis file.  I made a branch and I think I fixed it.

**Comment by delgrecoj** [comment]
It looks like that solves the problem... it's showing the coverage report for that branch just fine.

**Comment by delgrecoj** [comment]
merged in #106.
