### ISSUE TITLE
Retrieve data from Google Forms/Sheets with security measures

### ISSUE THREAD

**Issue by eltmanm** [Accelegator/accelegator#12]
Look into google APIs to see whether we can auto-generate unique service accounts or prompt access upon use of the program. From there, reimplement the `spreadsheet.py` file from GatorGrouper so as to get the data from Google saved into a `.csv.` Document the steps needed for the user to access program(generate service ID), as well as how to update their information to the most recent version via running `spreadsheet.py`.

**Comment by eltmanm** [comment]
https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html

**Comment by sporrera** [comment]
@eltmanm, @Nikki-Luoma and I have tried unsuccessfully to reach you on slack about receiving specific assignments. If you are unable to meet today, @yeeunmariakim will provide us tasks to complete in lieu of this Issue. Please let us know

**Comment by eltmanm** [comment]
i apologize, however, I did respond earlier today on slack, practically any time today to meet works for me, in case you did not read that there, and I will also supply more detailed explanation of what we must do for this issue within the next few hours.

**Comment by eltmanm** [comment]
https://docs.google.com/spreadsheets/d/1JItQY2ajuEEZAhAkKruqvZjX_835n_z11MyfwZoLDnI/edit#gid=1612999528

https://docs.google.com/forms/d/1jaWmgZ75t66lg0Zbp_ypovomAuv4p48XAaXVnkMF9jk/edit

https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html

https://console.developers.google.com/apis/credentials/wizard?api=drive.googleapis.com&project=gatorgrouper&organizationId=814721766701

**Comment by Nikki-Luoma** [comment]
On Friday this group meet to discuss what needs to be done. We concluded that we could find out the legal aspects, including Allegheny College policies for sharing adviser information. We also talked about what format the Google Form should be in.

**Comment by Nikki-Luoma** [comment]
I have updated the Google Form to include the questions from the README. I also changed how some of the questions got answered.

**Comment by eltmanm** [comment]
cool. adding comments to the code in a couple minutes.

**Comment by sporrera** [comment]
I just pushed the markdown file called Legalities and Privacy to our branch. It is ready to be merged to master, either within README.md or individually.

**Comment by eltmanm** [comment]
okay.
will be adding and merging likely within the next hour.

**Comment by eltmanm** [comment]
fixed all including csv creation, the csv format is not yet properly generated yet, however. python experience lacking.
