### ISSUE TITLE
Implement display_show function

### ISSUE THREAD

**Issue by yeeunmariakim** [Accelegator/accelegator#14]
The starting file for this issue has been pushed to the branch `feature/i-14-display-show`. Checkout this branch instead of creating a new branch by running the command: `git checkout feature/i-14-display-show`. 

Assume an input of a tuple of tuples--the outer tuple represents one student, and the inner tuples represent the fields and responses for that student. Something like this: 
```
tuple_of_tuples = (("timestamp", "id", "12345"), ("timestamp", "email", "maria@maria.com") ... )
```
The behavior of the `display_show` function should be to display the data in the tuple in the following format:
```
field                                                       timestamp
response
```
Specifically, each line of text should not exceed 80 characters. That is, if a response exceeds 80 characters, make it go on a new line without cutting words in half. The fields and timestamps will look a bit different in the end, but for now, display them as they are. I have included example data in `display_data.py` to start with. This data will undergo changes by the end as it becomes more clear on @delgrecoj's front about what data will be outputted by the Query functionality. But it will be a good starting point.

**Comment by lylet-AC** [comment]
So the main question I have is how I would extract the persons name from the outer tuple?  What are my inputs? Is my function going to prompt the user for input, or will that be taken care of elsewhere?

**Comment by yeeunmariakim** [comment]
The REPL takes care of the prompting. As I wrote above, the input is a tuple of tuples. One of the tuples in the outer tuple the advisee's name. It may help to look at the example data I provided for you.

**Comment by lylet-AC** [comment]
Yeah, I guess what I mean to say is, will I need to search through tuples based on a name provided by the outer tuple?  So the way I'm thinking of implementing this is by checking if the user input is equal to my first tuple's index.  So will I need to ask the user which student they are looking for and then output the rest of the information for the corresponding tuple?

**Comment by lylet-AC** [comment]
Or is all of this logic handled externally and Ill only get the data for one student?

**Comment by yeeunmariakim** [comment]
Your second comment is correct. All you have to implement is taking in a tuple of tuples (which represents one student) and displaying the information in that tuple as I've written above.

**Comment by yeeunmariakim** [comment]
You will need to implement only the one function I provided a starting file for.

**Comment by lylet-AC** [comment]
testcase for display_show will not run due to an error:
`"no module named colors"`
possibly related to my pc setup

**Comment by yeeunmariakim** [comment]
Address in PR #33
