### ISSUE TITLE
Set up Travis CI with Coveralls integration

### ISSUE THREAD

**Issue by yeeunmariakim** [Accelegator/accelegator#2]

**Comment by sutterj** [comment]
Do we want to use autopep8 and pytest-flake8 as in the last project?

**Comment by yeeunmariakim** [comment]
@Andre-Bryan status update on this feature?

**Comment by Andre-Bryan** [comment]
Still don't have admin rights.

**Comment by yeeunmariakim** [comment]
![957bb853-6028-408c-b3d7-74c5e77fef57](https://user-images.githubusercontent.com/19576999/32114114-73900ede-bb10-11e7-9ed5-0f9ed812e582.jpeg)
@Andre-Bryan that is strange. I made you an owner of the repository a few days ago and this is what I see in the organization page.

**Comment by yeeunmariakim** [comment]
Sorry, didn’t mean to close this issue.
