### ISSUE TITLE
Implement display_help_with_command function

### ISSUE THREAD

**Issue by yeeunmariakim** [Accelegator/accelegator#20]
The starting file for this issue has been pushed to the branch `feature/i-20-display-help-with-command`. Checkout this branch instead of creating a new branch by running the command: `git checkout feature/i-20-display-help-with-command`.

![accelegator-planning-photo](https://user-images.githubusercontent.com/19576999/32033950-be8f7426-b9dd-11e7-90fb-e748de389cbe.jpg)
When a user types `help show` into the REPL, the function `display_help_with_command` function should be executed. This function displays a more verbose description of the command, in this case `show` and its valid arguments. For example, the `show` command can take two types of arguments: `show <email>` or `show <email> <field>`.
The output of running `help show` might look like this:
```
show
----
show <email>                    
Description: Shows for the advisee specified by <email> their most recent response to each field and their timestamps.
Valid arguments:  Emails should be written without the '@allegheny.edu' ending. Ex. 'kimy'.

show <email> <field>
Description: Shows for the advisee specified by <email> all their responses for the field specifield by <field>.
Valid arguments:  Emails should be written without the '@allegheny.edu' ending. Ex. 'kimy'.
Fields can be any of the following:
allegheny-email
id
name
resume
cover-letter
four-year-plan
grad-year
github
website
linkedin
twitter
fav-major-class
fav-nonmajor-class
career
academic-interests
personal-interests
tech-strengths
tech-weaknesses
academic-status
personal-status
advisor-questions
```

**Comment by karolvargas** [comment]
currently adding functions to display detailed descriptions of each command which can be used in accelegator

**Comment by karolvargas** [comment]
added most of the functions and arguments for this issue. going to finish the last few functions and test cases tommorow before noon

**Comment by karolvargas** [comment]
finished refactoring the functions and created pull request for this issue, please review at your nearest convenience and let me know if there are any other additions you would like me to add

**Comment by karolvargas** [comment]
function passed build and refactoring method is solid I believe but the accelegator is conflicting somehow with this function
