### ISSUE TITLE
Implement `determine_latest` function

### ISSUE THREAD

**Issue by delgrecoj** [Accelegator/accelegator#28]
(scaffolded in the `queries.py` module, waiting on merge of pull request #27 which addresses issue #26)

**Comment by delgrecoj** [comment]
@mendezjw, @TravisThomasAC -- status update on this issue?

**Comment by TravisThomasAC** [comment]
will update after work is done tonight.

**Comment by delgrecoj** [comment]
Just for clarification, this function needs to take in the dataframe, email, field, and date, and return a boolean;
- `true` if the provided date and field is the latest response in the dataframe
- `false` if the provided date and field is not the latest response in the dataframe
Updated return signatures can be found in the branch for issue #31.

**Comment by TravisThomasAC** [comment]
Posting link to pandas.Index API for reference

**Comment by delgrecoj** [comment]
working implementation in the branch for issue #31; passing test suite with several tests using it implicitly; closing.
