### ISSUE TITLE
Implement `query_show` and `query_show_field` functions

### ISSUE THREAD

**Issue by delgrecoj** [Accelegator/accelegator#30]
(scaffolded in the `queries.py` module, waiting on merge of pull request #27 which addresses issue #26)

The latter function looks like a good candidate for filtering the input columns and sending the input to the former function.

**Comment by delgrecoj** [comment]
@mendezjw, @TravisThomasAC -- status update on this issue?

**Comment by TravisThomasAC** [comment]
will update after work is done tonight.

**Comment by delgrecoj** [comment]
Just for clarification, the `query_show` function needs to take in the dataframe and an email, and return a tuple containing the email, and a list of tuples, each of which contains a tuple of the timestamp and whether it's the latest response or not, the field, and the response.  Each of the tuples in the list represents the latest response in the dataframe for each field.

The `query_show_field` function needs to take in the same arguments, as well as a field... it will have to return a tuple containing the email, the field, and a list of tuples, each of which contains a tuple of the timestamp and whether it's the latest response or not, and the response.  Each of the tuples in the list represents a response in the dataframe for that student and that field, and are contained in a list because we do not know how many responses they may have had.

This is perhaps more clear in code form, which can be found in the branch for issue #31.

**Comment by mendezjw** [comment]
These links may be helpful for finding values in a dataframe
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Index.html
https://stackoverflow.com/questions/40656090/how-you-use-query-with-pandas-and-numpy

**Comment by delgrecoj** [comment]
`query_show_field` function has an implementation now in `queries.py`.

**Comment by delgrecoj** [comment]
`query_show_field` function now has working implementation and test cases; onto `query_show`.

**Comment by delgrecoj** [comment]
implemented in the branch for #31; passing testsuite; closing.
