### ISSUE TITLE
Getting test cases to pass

### ISSUE THREAD

**Issue by burrowss** [Accelegator/accelegator#56]
Currently, there seems to be one test case that is failing in the queries.py file. If someone could help me with figuring it out that would be great.

**Comment by delgrecoj** [comment]
Swap the order of the second and third arguments in that call (line 56 of `tests/test_queries.py`).

(swap `"rewq"` with `3`)

(someone's refactoring of the REPL modified the query function when it was supposed to modify the REPL function instead, thus breaking the wrong tests...)

**Comment by burrowss** [comment]
Thank you. that fixed it
