### ISSUE TITLE
Correct links

### ISSUE THREAD

**Issue by castellanosr** [Accelegator/accelegator#77]
https://github.com/Accelegator/accelegator needs to be displayed in the terminal after the welcome message, but before the rest of the program runs.

**Comment by delgrecoj** [comment]
None of the links in `README.md` or `LEGAL.md` appear to be broken... could you please clarify this issue?

**Comment by burrowss** [comment]
Same here. All of the links in the md files worked

**Comment by burrowss** [comment]
I can do this quickly

**Comment by castellanosr** [comment]
We both fixed it at the same time from different computers, check for merge conflicts.
