### ISSUE TITLE
No file titled "AGAuthKey.json

### ISSUE THREAD

**Issue by lylet-AC** [Accelegator/accelegator#79]
Upon running accelegator, it tells me there is no file called AGAuthKey.json, which we removed from the repo for security reasons.

**Comment by eltmanm** [comment]
that should be found on slack and i can pass that to you specifically if need be

**Comment by millinj2** [comment]
For security reasons the .json file should not be committed to the repository.

**Comment by eltmanm** [comment]
it is now in the labs channel on slack
download it but do not commit it with the repository when making updates

**Comment by eltmanm** [comment]
thank you @yeeunmariakim
