### ISSUE TITLE
Show With Field shows response prior to one requested

### ISSUE THREAD

**Issue by lylet-AC** [Accelegator/accelegator#97]
Show command with field shows the response before the one requested.  For example, running accelegator for toccin@allegheny.edu given the: `show toccin@allegheny.edu 21` shows the response for the 20th question instead of the 21st.

**Comment by lylet-AC** [comment]
Okay, I didn't

**Comment by lylet-AC** [comment]
I didn't test it first, sorry!

**Comment by yeeunmariakim** [comment]
@lylet-AC I have resolved this in my current pull request

**Comment by delgrecoj** [comment]
merged in #101.
