### ISSUE TITLE
Error when running ```python3 accelegator.py```

### ISSUE THREAD

**Issue by sporrera** [Accelegator/accelegator#99]
I just pulled from the master branch to ensure that I had the most current version of the program and attempted to run the program so I could analyze the results.  However, it gave me this error:

![screen shot 2017-11-13 at 10 17 09 pm](https://user-images.githubusercontent.com/22895356/32761262-6d909a04-c8c0-11e7-9d72-aeb6d783c773.png)

Does anyone have any idea what is going on here?

**Comment by delgrecoj** [comment]
It's missing a comma in that file... but that's just the template file anyway, you need the actual one which can be found on `labs` channel on Slack.

**Comment by sporrera** [comment]
Thanks for the response, @delgrecoj !

**Comment by delgrecoj** [comment]
Pushed the comma fix directly to master... bad form, but seemed worse to go through the whole process for a literally one character fix.
